### ISSUE TITLE
no Router found in OSGi

### ISSUE THREAD

**Issue by fohnbit** [bitletorg/weupnp#14]
I wrote a standalone and a plugin for an OSGi system.
At the OSGi I has to set the sa.jar and javax.xml-1.3.4.jar in Buildpath.

The Standalone are find on my Linux system thr router.
The OSGI Plugin not.

But same code.

I guess it is a problem with the sax.jar and javax.xml version?

Which version should I use?

**Comment by fohnbit** [comment]
OK, found a solution. Has to add 3 library to the buildpath:
sax.jar
javax.xml.jar
xerces.jar

**Comment by abahgat** [comment]
Thanks for documenting the solution as well, I'm closing this issue as resolved. Let us know if you need any more help.
